✨ 新增流式消息、反馈按钮、推荐按钮、赞踩事件
nonebot/adapter-qq pull request #106
Opened 2024-04-11 02:49 UTC by KimigaiiWuyi

先不要合

2025-06-24 13:06 UTC, KimigaiiWuyi commented
代码参考
```python
from nonebot.adapters.qq.event import MessageEvent
from nonebot.adapters.qq.message import (
    MessageSegment,
    Message,
)
from nonebot.adapters.qq.models.qq import (
    PromptContent,
    MessagePromptKeyboard,
    PromptKeyboardModel,
    PromptRow,
    PromptRenderData,
    PromptButton,
    PromptAction,
)

from nonebot import on_message
from nonebot.typing import T_State
from nonebot.adapters import Bot
import time

test = on_message()

LABEL = '''## 你好！我是AI助手啪木！'''


def stream_simulator(text: str, delay: float = 0.05):
    for char in text:
        yield char
        time.sleep(delay)


# 流式响应
@test.handle()
async def test_handle(bot: Bot, event: MessageEvent, state: T_State):
    if event.get_plaintext() == "测试":
        stream_generator = stream_simulator(LABEL)

        index = 0
        _id = None
        _state = 1
        for char_chunk in stream_generator:
            message = Message()
            message += MessageSegment.markdown(char_chunk)
            message += MessageSegment.stream(_state, _id, index)
            msgReturn = await test.send(message)
            _id = msgReturn.id
            index += 1
            _state = 11

        # 生成结束 11 表示还有气泡消息需要等待 10 则直接结束
        message = Message()
        message += MessageSegment.markdown('生成结束！')
        message += MessageSegment.stream(11, _id, index)
        msgReturn = await test.send(message)
        _id = msgReturn.id
        index += 1

        # 发送一条建议气泡 20 表示正式结束
        message = Message()
        message += MessageSegment.markdown('此时推荐消息生成完毕！')
        message += MessageSegment.stream(20, _id, index)

        keyboard = MessagePromptKeyboard(
            keyboard=PromptKeyboardModel(
                content=PromptContent(
                    rows=[
                        PromptRow(
                            buttons=[
                                PromptButton(
                                    render_data=PromptRenderData(label='第一行第一个'),
                                    action=PromptAction(type=2),
                                ),
                                PromptButton(
                                    render_data=PromptRenderData(label='第一行第二个'),
                                    action=PromptAction(type=2),
                                ),
                            ]
                        )
                    ]
                )
            )
        )
        message += MessageSegment.prompt_keyboard(keyboard)
        msgReturn = await test.send(message)

```

2025-06-28 14:23 UTC, yanyongyu commented on nonebot/adapters/qq/event.py
> +    _reply_seq: int = 0
看到了文档里说默认是 1，看来是改成 1 开始了？

2025-06-28 14:25 UTC, yanyongyu requested changes

2025-06-28 14:25 UTC, yanyongyu commented on nonebot/adapters/qq/models/qq.py
> +from typing import List, Literal, Optional
```suggestion
from typing import Literal, Optional
```

2025-06-28 14:25 UTC, yanyongyu commented on nonebot/adapters/qq/models/qq.py
> +    buttons: List[PromptButton]
```suggestion
    buttons: list[PromptButton]
```

2025-06-28 14:25 UTC, yanyongyu commented on nonebot/adapters/qq/models/qq.py
> +    rows: List[PromptRow]
```suggestion
    rows: list[PromptRow]
```

2025-06-28 14:41 UTC, yanyongyu approved these changes

2025-06-28 15:17 UTC, yanyongyu requested changes

2025-06-28 15:17 UTC, yanyongyu commented on nonebot/adapters/qq/models/qq.py
> +    label: str
这两个model名字怎么一样

2025-06-30 12:42 UTC, KimigaiiWuyi commented on nonebot/adapters/qq/models/qq.py
> +    label: str
已解决

2025-06-30 15:30 UTC, merged