Fix reply same message more than once in group, perhaps c2c
nonebot/adapter-qq pull request #80
Opened 2023-11-17 05:34 UTC by Dreamail

2023-11-17 05:47 UTC, yanyongyu requested changes

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +        msg_seq: Optional[str] = None,
```suggestion
        msg_seq: Optional[int] = None,
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +        msg_seq: Optional[str] = None,
```suggestion
        msg_seq: Optional[int] = None,
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +            event.msg_seq += 1
```suggestion
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +                msg_seq=event.msg_seq,
```suggestion
                **kwargs,
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +            event.msg_seq += 1
```suggestion
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +                msg_seq=event.msg_seq,
```suggestion
                **kwargs,
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +        msg_seq: Optional[str] = None,
```suggestion
        msg_seq: Optional[int] = None,
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +        msg_seq: Optional[str] = None,
```suggestion
        msg_seq: Optional[int] = None,
```

2023-11-17 05:47 UTC, yanyongyu commented on nonebot/adapters/qq/event.py
> +    msg_seq: int = -1
```suggestion
```

2023-11-17 06:10 UTC, yanyongyu requested changes

2023-11-17 06:10 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +                msg_seq=msg_seq,
```suggestion
```

2023-11-17 06:10 UTC, yanyongyu commented on nonebot/adapters/qq/bot.py
> +                    "msg_seq": msg_seq,
```suggestion
```

2023-11-17 06:11 UTC, yanyongyu commented
只有私聊有msg seq

2023-11-17 06:19 UTC, Dreamail commented
群聊是有的，seq不自增会导致回复同一消息报错

2023-11-17 06:21 UTC, Dreamail commented
![image](https://github.com/nonebot/adapter-qq/assets/46253320/ec99aa8c-c683-489d-a9be-266c83669745)
我自己也测试过了，

2023-11-17 06:23 UTC, yanyongyu commented
所以是官方文档这边漏写了？如果不传msg seq发送两天消息会失败？

https://bot.q.qq.com/wiki/develop/api-231017/server-inter/message/send-receive/send.html#%E7%BE%A4%E8%81%8A

2023-11-17 06:30 UTC, yanyongyu commented
那把上面几个改动更新一下吧

2023-11-17 15:45 UTC, Dreamail commented
好了应该

2023-11-18 07:02 UTC, yanyongyu approved these changes

2023-11-18 07:02 UTC, merged